homepage:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

register:
    path: /register
    controller: App\Controller\RegistrationController::register




