user_show:
  controller: App\Controller\UserController::show
  path:
    hr: /hr/korisnički-profil
    en: /profile

user_edit:
  controller: App\Controller\UserController::edit
  path:
    hr: /hr/korisnički-profil/uređivanje/{user}
    en: /profile/edit/{user}

logout:
  controller: App\Controller\SecurityController::logout
  path:
    hr: /hr/odjava
    en: /logout

login:
  controller: App\Controller\SecurityController::login
  path:
    hr: /hr/prijava
    en: /login

register:
  controller: App\Controller\RegistrationController::register
  path:
    hr: /hr/registracija
    en: /register

post_index:
  controller: App\Controller\PostController::index
  path:
    hr: /hr/
    en: /

post_show:
  controller: App\Controller\PostController::show
  path:
    hr: /hr/objave/{post}
    en: /posts/{post}

ajax_post_index:
  controller: App\Controller\PostController::ajaxIndex
  path: /ajax-post

ajax_favorite:
  controller: App\Controller\FavoriteController::ajaxFavorite
  path: /ajax-favorite

ajax_comment:
  controller: App\Controller\CommentController::ajaxComment
  path: /ajax-comment

ajax_comment_delete:
  controller: App\Controller\CommentController::ajaxDelete
  path: /ajax-delete

ajax_like:
  controller: App\Controller\LikeCounterController::ajaxLike
  path: /ajax-like

tag_index:
  controller: App\Controller\Admin\TagController::index
  path:
    hr: /hr/admin/tagovi
    en: /admin/tags

tag_new:
  controller: App\Controller\Admin\TagController::new
  path:
    hr: /hr/admin/tagovi/novi
    en: /admin/tags/new

tag_show:
  controller: App\Controller\Admin\TagController::show
  path:
    hr: /hr/admin/tagovi/{tag}
    en: /admin/tags/{tag}

tag_edit:
  controller: App\Controller\Admin\TagController::edit
  path:
    hr: /hr/admin/tagovi/{tag}/uredivanje
    en: /admin/tags/{tag}/edit

tag_delete:
  controller: App\Controller\Admin\TagController::delete
  path:
    hr: /hr/admin/tagovi/{tag}/obriši
    en: /admin/tags/{tag}/delete

post_new:
  controller: App\Controller\Admin\PostController::new
  path:
    hr: /hr/admin/objave/nova
    en: /admin/posts/new

post_edit:
  controller: App\Controller\Admin\PostController::edit
  path:
    hr: /hr/admin/objave/{post}/uredivanje
    en: /admin/posts/{post}/edit

post_delete:
  controller: App\Controller\Admin\PostController::delete
  path:
    hr: /hr/admin/objave/{post}
    en: /admin/posts/{post}